// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/garage-svc.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
	models "models"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GarageUserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarageUserId) Reset()         { *m = GarageUserId{} }
func (m *GarageUserId) String() string { return proto.CompactTextString(m) }
func (*GarageUserId) ProtoMessage()    {}
func (*GarageUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0a1c31559b3f635, []int{0}
}

func (m *GarageUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageUserId.Unmarshal(m, b)
}
func (m *GarageUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageUserId.Marshal(b, m, deterministic)
}
func (m *GarageUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageUserId.Merge(m, src)
}
func (m *GarageUserId) XXX_Size() int {
	return xxx_messageInfo_GarageUserId.Size(m)
}
func (m *GarageUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageUserId.DiscardUnknown(m)
}

var xxx_messageInfo_GarageUserId proto.InternalMessageInfo

func (m *GarageUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GarageAndUserId struct {
	UserId               string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Garage               *models.Garage `protobuf:"bytes,2,opt,name=garage,proto3" json:"garage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GarageAndUserId) Reset()         { *m = GarageAndUserId{} }
func (m *GarageAndUserId) String() string { return proto.CompactTextString(m) }
func (*GarageAndUserId) ProtoMessage()    {}
func (*GarageAndUserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0a1c31559b3f635, []int{1}
}

func (m *GarageAndUserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageAndUserId.Unmarshal(m, b)
}
func (m *GarageAndUserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageAndUserId.Marshal(b, m, deterministic)
}
func (m *GarageAndUserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageAndUserId.Merge(m, src)
}
func (m *GarageAndUserId) XXX_Size() int {
	return xxx_messageInfo_GarageAndUserId.Size(m)
}
func (m *GarageAndUserId) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageAndUserId.DiscardUnknown(m)
}

var xxx_messageInfo_GarageAndUserId proto.InternalMessageInfo

func (m *GarageAndUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GarageAndUserId) GetGarage() *models.Garage {
	if m != nil {
		return m.Garage
	}
	return nil
}

func init() {
	proto.RegisterType((*GarageUserId)(nil), "services.GarageUserId")
	proto.RegisterType((*GarageAndUserId)(nil), "services.GarageAndUserId")
}

func init() { proto.RegisterFile("services/garage-svc.proto", fileDescriptor_f0a1c31559b3f635) }

var fileDescriptor_f0a1c31559b3f635 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x4f, 0x4f, 0x2c, 0x4a, 0x4c, 0x4f, 0xd5, 0x2d, 0x2e, 0x4b, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x49, 0x49, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7,
	0xa4, 0xea, 0x83, 0xc5, 0x93, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0xca, 0xa4,
	0x84, 0x73, 0xf3, 0x53, 0x52, 0x73, 0x60, 0xfa, 0x21, 0x82, 0x4a, 0xea, 0x5c, 0x3c, 0xee, 0x60,
	0x7e, 0x68, 0x71, 0x6a, 0x91, 0x67, 0x8a, 0x90, 0x38, 0x17, 0x7b, 0x69, 0x71, 0x6a, 0x51, 0x7c,
	0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x5b, 0x29, 0x58, 0x42, 0x29, 0x88, 0x8b,
	0x1f, 0xa2, 0xd0, 0x31, 0x2f, 0x85, 0x80, 0x5a, 0x21, 0x35, 0x2e, 0x36, 0x88, 0x25, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x7c, 0x7a, 0x10, 0xab, 0xf5, 0x20, 0x26, 0x04, 0x41, 0x65, 0x8d,
	0xaa, 0xb9, 0xd8, 0x21, 0x22, 0xc5, 0x42, 0x26, 0x5c, 0x2c, 0x3e, 0x99, 0xc5, 0x25, 0x42, 0x62,
	0x7a, 0x30, 0xcf, 0xe8, 0x21, 0xbb, 0x4b, 0x4a, 0x08, 0xd5, 0x08, 0x90, 0x5a, 0x25, 0x06, 0x21,
	0x2b, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x49, 0x74, 0x4d, 0x70, 0x37, 0x4a, 0x89, 0xe9, 0x41,
	0x82, 0x44, 0x0f, 0x16, 0x24, 0x7a, 0xae, 0xa0, 0x20, 0x51, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x55, 0xc3, 0xef, 0x61, 0x59, 0x01, 0x00, 0x00,
}
