// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/garage.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	models/garage.proto
	models/user.proto

It has these top-level messages:
	GarageCoordinate
	Garage
	GarageList
	GarageListByUser
	GarageUserId
	GarageAndUserId
	User
	UserList
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GarageCoordinate struct {
	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GarageCoordinate) Reset()                    { *m = GarageCoordinate{} }
func (m *GarageCoordinate) String() string            { return proto.CompactTextString(m) }
func (*GarageCoordinate) ProtoMessage()               {}
func (*GarageCoordinate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GarageCoordinate) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GarageCoordinate) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Garage struct {
	Id         string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Coordinate *GarageCoordinate `protobuf:"bytes,3,opt,name=coordinate" json:"coordinate,omitempty"`
}

func (m *Garage) Reset()                    { *m = Garage{} }
func (m *Garage) String() string            { return proto.CompactTextString(m) }
func (*Garage) ProtoMessage()               {}
func (*Garage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Garage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Garage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Garage) GetCoordinate() *GarageCoordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type GarageList struct {
	List []*Garage `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *GarageList) Reset()                    { *m = GarageList{} }
func (m *GarageList) String() string            { return proto.CompactTextString(m) }
func (*GarageList) ProtoMessage()               {}
func (*GarageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GarageList) GetList() []*Garage {
	if m != nil {
		return m.List
	}
	return nil
}

type GarageListByUser struct {
	List map[string]*GarageList `protobuf:"bytes,1,rep,name=list" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GarageListByUser) Reset()                    { *m = GarageListByUser{} }
func (m *GarageListByUser) String() string            { return proto.CompactTextString(m) }
func (*GarageListByUser) ProtoMessage()               {}
func (*GarageListByUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GarageListByUser) GetList() map[string]*GarageList {
	if m != nil {
		return m.List
	}
	return nil
}

type GarageUserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GarageUserId) Reset()                    { *m = GarageUserId{} }
func (m *GarageUserId) String() string            { return proto.CompactTextString(m) }
func (*GarageUserId) ProtoMessage()               {}
func (*GarageUserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GarageUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GarageAndUserId struct {
	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Garage *Garage `protobuf:"bytes,2,opt,name=garage" json:"garage,omitempty"`
}

func (m *GarageAndUserId) Reset()                    { *m = GarageAndUserId{} }
func (m *GarageAndUserId) String() string            { return proto.CompactTextString(m) }
func (*GarageAndUserId) ProtoMessage()               {}
func (*GarageAndUserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GarageAndUserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GarageAndUserId) GetGarage() *Garage {
	if m != nil {
		return m.Garage
	}
	return nil
}

func init() {
	proto.RegisterType((*GarageCoordinate)(nil), "model.GarageCoordinate")
	proto.RegisterType((*Garage)(nil), "model.Garage")
	proto.RegisterType((*GarageList)(nil), "model.GarageList")
	proto.RegisterType((*GarageListByUser)(nil), "model.GarageListByUser")
	proto.RegisterType((*GarageUserId)(nil), "model.GarageUserId")
	proto.RegisterType((*GarageAndUserId)(nil), "model.GarageAndUserId")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Garages service

type GaragesClient interface {
	List(ctx context.Context, in *GarageUserId, opts ...grpc.CallOption) (*GarageList, error)
	Add(ctx context.Context, in *GarageAndUserId, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type garagesClient struct {
	cc *grpc.ClientConn
}

func NewGaragesClient(cc *grpc.ClientConn) GaragesClient {
	return &garagesClient{cc}
}

func (c *garagesClient) List(ctx context.Context, in *GarageUserId, opts ...grpc.CallOption) (*GarageList, error) {
	out := new(GarageList)
	err := grpc.Invoke(ctx, "/model.Garages/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garagesClient) Add(ctx context.Context, in *GarageAndUserId, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/model.Garages/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Garages service

type GaragesServer interface {
	List(context.Context, *GarageUserId) (*GarageList, error)
	Add(context.Context, *GarageAndUserId) (*google_protobuf.Empty, error)
}

func RegisterGaragesServer(s *grpc.Server, srv GaragesServer) {
	s.RegisterService(&_Garages_serviceDesc, srv)
}

func _Garages_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarageUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaragesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Garages/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaragesServer).List(ctx, req.(*GarageUserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Garages_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarageAndUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaragesServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Garages/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaragesServer).Add(ctx, req.(*GarageAndUserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Garages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Garages",
	HandlerType: (*GaragesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Garages_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Garages_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models/garage.proto",
}

func init() { proto.RegisterFile("models/garage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xa6, 0x2d, 0x94, 0xdb, 0xc3, 0xbd, 0x57, 0x3c, 0x24, 0x40, 0xaa, 0x0b, 0x98, 0xc4, 0xc0,
	0xaa, 0x35, 0x35, 0x06, 0xe3, 0x0e, 0x0d, 0x31, 0x1a, 0x36, 0x36, 0x71, 0x6d, 0x8a, 0x33, 0x36,
	0x8d, 0xa5, 0x43, 0xda, 0xa9, 0x49, 0x1f, 0xc4, 0xf7, 0x35, 0x9d, 0x81, 0x62, 0x61, 0xe1, 0x6e,
	0xe6, 0xfb, 0x39, 0x7f, 0xf9, 0xa0, 0xb7, 0xe6, 0x94, 0xc5, 0x99, 0x1b, 0x06, 0x69, 0x10, 0x32,
	0x67, 0x93, 0x72, 0xc1, 0xb1, 0x25, 0x41, 0xfb, 0x2c, 0xe4, 0x3c, 0x8c, 0x99, 0x2b, 0xc1, 0x55,
	0xfe, 0xee, 0xb2, 0xf5, 0x46, 0x14, 0x4a, 0x43, 0x96, 0xd0, 0x7d, 0x90, 0x9e, 0x7b, 0xce, 0x53,
	0x1a, 0x25, 0x81, 0x60, 0x68, 0xc3, 0x9f, 0x38, 0x10, 0x91, 0xc8, 0x29, 0x1b, 0x6a, 0x23, 0x6d,
	0xaa, 0xfb, 0xd5, 0x1f, 0xcf, 0xc1, 0x8a, 0x79, 0x12, 0x2a, 0x52, 0x97, 0xe4, 0x1e, 0x20, 0x0c,
	0x4c, 0x55, 0x0d, 0xff, 0x83, 0x1e, 0x51, 0xe9, 0xb6, 0x7c, 0x3d, 0xa2, 0x88, 0xd0, 0x4c, 0x82,
	0xb5, 0xb2, 0x58, 0xbe, 0x7c, 0xe3, 0x0c, 0xe0, 0xad, 0xea, 0x3a, 0x34, 0x46, 0xda, 0xb4, 0xe3,
	0x0d, 0x1c, 0x39, 0xb4, 0x73, 0x38, 0x94, 0xff, 0x43, 0x4a, 0x5c, 0x00, 0xc5, 0x2f, 0xa3, 0x4c,
	0xe0, 0x18, 0x9a, 0x71, 0x94, 0x89, 0xa1, 0x36, 0x32, 0xa6, 0x1d, 0xef, 0x5f, 0xad, 0x80, 0x2f,
	0x29, 0xf2, 0xa5, 0xed, 0xd6, 0x2c, 0x1d, 0x77, 0xc5, 0x4b, 0xc6, 0x52, 0xbc, 0xae, 0xf9, 0xc6,
	0x35, 0xdf, 0x5e, 0xe6, 0x94, 0xcf, 0x45, 0x22, 0xd2, 0x42, 0xd5, 0xb2, 0x9f, 0xc0, 0xaa, 0x20,
	0xec, 0x82, 0xf1, 0xc1, 0x8a, 0xed, 0x9e, 0xe5, 0x13, 0x27, 0xd0, 0xfa, 0x0c, 0xe2, 0x5c, 0x6d,
	0xda, 0xf1, 0x4e, 0x8f, 0xca, 0xfa, 0x8a, 0xbf, 0xd5, 0x6f, 0x34, 0x32, 0x81, 0xbf, 0x8a, 0x28,
	0x3b, 0x3d, 0x52, 0x1c, 0x40, 0x3b, 0xcf, 0x58, 0xfa, 0x5a, 0x9d, 0xce, 0xcc, 0x25, 0x41, 0x9e,
	0xe1, 0x44, 0x09, 0xe7, 0x09, 0xfd, 0x45, 0x8b, 0x17, 0x60, 0xaa, 0x18, 0x6c, 0x47, 0x38, 0xb8,
	0xc8, 0x96, 0xf4, 0x04, 0xb4, 0x15, 0x92, 0xe1, 0x25, 0x34, 0xe5, 0x25, 0x7b, 0x35, 0xa5, 0xea,
	0x63, 0x1f, 0x6f, 0x40, 0x1a, 0x38, 0x03, 0x63, 0x4e, 0x29, 0xf6, 0x6b, 0x5c, 0x35, 0x9b, 0xdd,
	0x77, 0x54, 0xe6, 0x9c, 0x5d, 0xe6, 0x9c, 0x45, 0x99, 0x39, 0xd2, 0x58, 0x99, 0x12, 0xb9, 0xfa,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x77, 0x3b, 0x19, 0xb1, 0x02, 0x00, 0x00,
}
