// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/garage.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GarageCoordinate struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarageCoordinate) Reset()         { *m = GarageCoordinate{} }
func (m *GarageCoordinate) String() string { return proto.CompactTextString(m) }
func (*GarageCoordinate) ProtoMessage()    {}
func (*GarageCoordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_45056989ff4b0a8f, []int{0}
}

func (m *GarageCoordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageCoordinate.Unmarshal(m, b)
}
func (m *GarageCoordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageCoordinate.Marshal(b, m, deterministic)
}
func (m *GarageCoordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageCoordinate.Merge(m, src)
}
func (m *GarageCoordinate) XXX_Size() int {
	return xxx_messageInfo_GarageCoordinate.Size(m)
}
func (m *GarageCoordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageCoordinate.DiscardUnknown(m)
}

var xxx_messageInfo_GarageCoordinate proto.InternalMessageInfo

func (m *GarageCoordinate) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GarageCoordinate) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Garage struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coordinate           *GarageCoordinate `protobuf:"bytes,3,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Garage) Reset()         { *m = Garage{} }
func (m *Garage) String() string { return proto.CompactTextString(m) }
func (*Garage) ProtoMessage()    {}
func (*Garage) Descriptor() ([]byte, []int) {
	return fileDescriptor_45056989ff4b0a8f, []int{1}
}

func (m *Garage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Garage.Unmarshal(m, b)
}
func (m *Garage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Garage.Marshal(b, m, deterministic)
}
func (m *Garage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Garage.Merge(m, src)
}
func (m *Garage) XXX_Size() int {
	return xxx_messageInfo_Garage.Size(m)
}
func (m *Garage) XXX_DiscardUnknown() {
	xxx_messageInfo_Garage.DiscardUnknown(m)
}

var xxx_messageInfo_Garage proto.InternalMessageInfo

func (m *Garage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Garage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Garage) GetCoordinate() *GarageCoordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

type GarageList struct {
	List                 []*Garage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GarageList) Reset()         { *m = GarageList{} }
func (m *GarageList) String() string { return proto.CompactTextString(m) }
func (*GarageList) ProtoMessage()    {}
func (*GarageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_45056989ff4b0a8f, []int{2}
}

func (m *GarageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageList.Unmarshal(m, b)
}
func (m *GarageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageList.Marshal(b, m, deterministic)
}
func (m *GarageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageList.Merge(m, src)
}
func (m *GarageList) XXX_Size() int {
	return xxx_messageInfo_GarageList.Size(m)
}
func (m *GarageList) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageList.DiscardUnknown(m)
}

var xxx_messageInfo_GarageList proto.InternalMessageInfo

func (m *GarageList) GetList() []*Garage {
	if m != nil {
		return m.List
	}
	return nil
}

type GarageListByUser struct {
	List                 map[string]*GarageList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GarageListByUser) Reset()         { *m = GarageListByUser{} }
func (m *GarageListByUser) String() string { return proto.CompactTextString(m) }
func (*GarageListByUser) ProtoMessage()    {}
func (*GarageListByUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_45056989ff4b0a8f, []int{3}
}

func (m *GarageListByUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarageListByUser.Unmarshal(m, b)
}
func (m *GarageListByUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarageListByUser.Marshal(b, m, deterministic)
}
func (m *GarageListByUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarageListByUser.Merge(m, src)
}
func (m *GarageListByUser) XXX_Size() int {
	return xxx_messageInfo_GarageListByUser.Size(m)
}
func (m *GarageListByUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GarageListByUser.DiscardUnknown(m)
}

var xxx_messageInfo_GarageListByUser proto.InternalMessageInfo

func (m *GarageListByUser) GetList() map[string]*GarageList {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*GarageCoordinate)(nil), "models.GarageCoordinate")
	proto.RegisterType((*Garage)(nil), "models.Garage")
	proto.RegisterType((*GarageList)(nil), "models.GarageList")
	proto.RegisterType((*GarageListByUser)(nil), "models.GarageListByUser")
	proto.RegisterMapType((map[string]*GarageList)(nil), "models.GarageListByUser.ListEntry")
}

func init() { proto.RegisterFile("models/garage.proto", fileDescriptor_45056989ff4b0a8f) }

var fileDescriptor_45056989ff4b0a8f = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0x25, 0xe9, 0x58, 0xec, 0x2d, 0x0c, 0xc3, 0x75, 0x53, 0x06, 0x17, 0x25, 0xab, 0xae, 0xaa,
	0x54, 0x90, 0xc1, 0xa5, 0x22, 0x2e, 0x9c, 0x55, 0xc0, 0x0f, 0x88, 0x26, 0x96, 0x60, 0xa6, 0x91,
	0x34, 0x23, 0xf4, 0x4b, 0xfc, 0x5d, 0x69, 0xa2, 0xad, 0xd5, 0xdd, 0xe9, 0x79, 0xf5, 0x1e, 0x02,
	0x67, 0x07, 0x2b, 0x95, 0xe9, 0x2f, 0x5a, 0xe1, 0x44, 0xab, 0xea, 0x77, 0x67, 0xbd, 0xc5, 0x34,
	0x92, 0x6c, 0x0f, 0x9b, 0x87, 0xc0, 0xdf, 0x59, 0xeb, 0xa4, 0xee, 0x84, 0x57, 0xb8, 0x85, 0x53,
	0x23, 0xbc, 0xf6, 0x47, 0xa9, 0x0a, 0x52, 0x92, 0x8a, 0xf2, 0xe9, 0x1b, 0xcf, 0x21, 0x33, 0xb6,
	0x6b, 0xa3, 0x48, 0x83, 0x38, 0x13, 0xec, 0x15, 0xd2, 0xd8, 0x86, 0x6b, 0xa0, 0x5a, 0x86, 0x74,
	0xc6, 0xa9, 0x96, 0x88, 0xb0, 0xea, 0xc4, 0x21, 0x46, 0x32, 0x1e, 0x30, 0xee, 0x00, 0x5e, 0xa6,
	0xbf, 0x16, 0x49, 0x49, 0xaa, 0xbc, 0x29, 0xea, 0x78, 0x58, 0xfd, 0xf7, 0x2a, 0xfe, 0xcb, 0xcb,
	0x2e, 0x01, 0xa2, 0xbe, 0xd7, 0xbd, 0x47, 0x06, 0x2b, 0xa3, 0x7b, 0x5f, 0x90, 0x32, 0xa9, 0xf2,
	0x66, 0xbd, 0x6c, 0xe0, 0x41, 0x63, 0x9f, 0xe4, 0x67, 0xe8, 0x18, 0xb9, 0x1d, 0x9e, 0x7a, 0xe5,
	0xf0, 0x7a, 0x11, 0x64, 0xcb, 0xe0, 0xec, 0xab, 0x47, 0x78, 0xdf, 0x79, 0x37, 0xc4, 0xb2, 0xed,
	0x23, 0x64, 0x13, 0x85, 0x1b, 0x48, 0xde, 0xd4, 0xf0, 0x3d, 0x75, 0x84, 0x58, 0xc1, 0xc9, 0x87,
	0x30, 0xc7, 0x38, 0x36, 0x6f, 0xf0, 0x7f, 0x2f, 0x8f, 0x86, 0x1b, 0xba, 0x23, 0xcf, 0x69, 0x78,
	0x90, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xef, 0x08, 0xec, 0xa7, 0x01, 0x00, 0x00,
}
