// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/user.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserGender int32

const (
	UserGender_UNDEFINED UserGender = 0
	UserGender_MALE      UserGender = 1
	UserGender_FEMALE    UserGender = 2
)

var UserGender_name = map[int32]string{
	0: "UNDEFINED",
	1: "MALE",
	2: "FEMALE",
}

var UserGender_value = map[string]int32{
	"UNDEFINED": 0,
	"MALE":      1,
	"FEMALE":    2,
}

func (x UserGender) String() string {
	return proto.EnumName(UserGender_name, int32(x))
}

func (UserGender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_74aea6fdcd620c44, []int{0}
}

type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string     `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Gender               UserGender `protobuf:"varint,4,opt,name=gender,proto3,enum=model.UserGender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_74aea6fdcd620c44, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetGender() UserGender {
	if m != nil {
		return m.Gender
	}
	return UserGender_UNDEFINED
}

type UserList struct {
	List                 []*User  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_74aea6fdcd620c44, []int{1}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.UserGender", UserGender_name, UserGender_value)
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*UserList)(nil), "model.UserList")
}

func init() { proto.RegisterFile("models/user.proto", fileDescriptor_74aea6fdcd620c44) }

var fileDescriptor_74aea6fdcd620c44 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x6b, 0xb3, 0x40,
	0x10, 0xc6, 0xd5, 0x6c, 0xc4, 0x4c, 0x78, 0xf3, 0x26, 0x73, 0x28, 0x62, 0x0f, 0x15, 0x4f, 0xb6,
	0x85, 0x15, 0xed, 0x27, 0x28, 0xc4, 0x94, 0x42, 0x9a, 0x83, 0x90, 0x0f, 0x90, 0xe0, 0x54, 0x04,
	0xcd, 0xda, 0x5d, 0x43, 0xe9, 0xb7, 0x2f, 0x4e, 0xfa, 0xc7, 0x4b, 0x6f, 0xe3, 0x6f, 0x7e, 0xf3,
	0xb8, 0x3c, 0xb0, 0x6a, 0x55, 0x49, 0x8d, 0x49, 0xce, 0x86, 0xb4, 0xec, 0xb4, 0xea, 0x15, 0x4e,
	0x19, 0x05, 0xd7, 0x95, 0x52, 0x55, 0x43, 0x09, 0xc3, 0xe3, 0xf9, 0x35, 0xa1, 0xb6, 0xeb, 0x3f,
	0x2e, 0x4e, 0xf4, 0x06, 0x62, 0x6f, 0x48, 0xe3, 0x02, 0x9c, 0xba, 0xf4, 0xed, 0xd0, 0x8e, 0x67,
	0x85, 0x53, 0x97, 0x88, 0x20, 0x4e, 0x87, 0x96, 0x7c, 0x87, 0x09, 0xcf, 0x18, 0x80, 0xd7, 0x1d,
	0x8c, 0x79, 0x57, 0xba, 0xf4, 0x27, 0xcc, 0x7f, 0xbe, 0xf1, 0x16, 0xdc, 0x8a, 0x4e, 0x25, 0x69,
	0x5f, 0x84, 0x76, 0xbc, 0xc8, 0x56, 0x92, 0x7f, 0x2e, 0x87, 0xf0, 0x27, 0x5e, 0x14, 0x5f, 0x42,
	0x74, 0x0f, 0xde, 0x40, 0xb7, 0xb5, 0xe9, 0xf1, 0x06, 0x44, 0x53, 0x9b, 0xde, 0xb7, 0xc3, 0x49,
	0x3c, 0xcf, 0xe6, 0xa3, 0xa3, 0x82, 0x17, 0x77, 0x29, 0xc0, 0x6f, 0x04, 0xfe, 0x83, 0xd9, 0x7e,
	0xb7, 0xce, 0x37, 0xcf, 0xbb, 0x7c, 0xbd, 0xb4, 0xd0, 0x03, 0xf1, 0xf2, 0xb8, 0xcd, 0x97, 0x36,
	0x02, 0xb8, 0x9b, 0x9c, 0x67, 0x27, 0x6b, 0x61, 0x3a, 0x9c, 0x18, 0x4c, 0xc1, 0x2b, 0xa8, 0xaa,
	0x4d, 0x4f, 0x1a, 0xc7, 0xd1, 0xc1, 0x95, 0xbc, 0x54, 0x22, 0xbf, 0x2b, 0x91, 0xf9, 0x50, 0x49,
	0x64, 0x61, 0x0a, 0x82, 0xdf, 0xf5, 0x87, 0x11, 0xfc, 0x1f, 0xc5, 0x0c, 0x62, 0x64, 0x1d, 0x5d,
	0x56, 0x1e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x16, 0x2f, 0x04, 0x81, 0x01, 0x00, 0x00,
}
